name: On Demand Formatting
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test format'
jobs:
  rebase:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write *.js .*.{js,yml} frontend/**/*.{js,vue,scss}
          only_changed: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
